package org.tu.varna.common;

public enum QuestionType {
    MULTIPLE_CHOICE, TRUE_FALSE, MATCHING, SHORT_ANSWER, NUMERICAL,
    ESSAY, CALCULATED, CALCULATED_MULTICHOICE, CALCULATED_SIMPLE, DRAG_AND_DROP_INTO_TEXT,
    DRAG_AND_DROP_ONTO_IMAGE, DRAG_AND_DROP_MARKERS, EMBEDDED_ANSWERS, RANDOM_SHORT_ANSWER_MATCHING,
    SELECT_MISSING_WORDS
}
